# version: 'v2.40.3-desktop.1'
services:
    nginx:
        image: lunahazuki2006/buscaminas:latest 
        container_name: buscaminas
        ports:
            - "8080:80" 
        volumes:
            - .:/usr/share/nginx/html:ro 